name: Feature request
description: Suggest an idea or improvement for this project
body:
  - type: textarea
    attributes:
      label: Problem
      description: |
        A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for contributing!
