-- This file is autogenerated from regen-schema.ts
CREATE TABLE IF NOT EXISTS love_waitlist (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_time TIMESTAMPTZ DEFAULT now() NOT NULL,
    email TEXT NOT NULL
);

-- Row Level Security
ALTER TABLE love_waitlist ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "anon insert" ON love_waitlist;
CREATE POLICY "anon insert" ON love_waitlist
    FOR INSERT WITH CHECK (true);

-- Indexes
-- Primary key automatically creates a unique index on id, so no additional index is needed.
