BEGIN;
\i backend/supabase/extensions.sql
\i backend/supabase/rebuild_profile_search.sql
\i backend/supabase/functions.sql
\i backend/supabase/firebase.sql
\i backend/supabase/users.sql
\i backend/supabase/profiles.sql
\i backend/supabase/private_user_message_channels.sql
\i backend/supabase/private_user_message_channel_members.sql
\i backend/supabase/private_users.sql
\i backend/supabase/private_user_messages.sql
\i backend/supabase/private_user_seen_message_channels.sql
\i backend/supabase/profile_comments.sql
\i backend/supabase/compatibility_prompts.sql
\i backend/supabase/compatibility_answers.sql
\i backend/supabase/compatibility_answers_free.sql
\i backend/supabase/compatibility_scores.sql
\i backend/supabase/profile_likes.sql
\i backend/supabase/profile_ships.sql
\i backend/supabase/profile_stars.sql
\i backend/supabase/user_events.sql
\i backend/supabase/user_notifications.sql
\i backend/supabase/functions_others.sql
\i backend/supabase/reports.sql
\i backend/supabase/bookmarked_searches.sql
\i backend/supabase/causes.sql
\i backend/supabase/causes_translations.sql
\i backend/supabase/contact.sql
\i backend/supabase/hidden_profiles.sql
\i backend/supabase/interests.sql
\i backend/supabase/interests_translations.sql
\i backend/supabase/push_subscriptions.sql
\i backend/supabase/push_subscriptions_mobile.sql
\i backend/supabase/user_activity.sql
\i backend/supabase/votes.sql
\i backend/supabase/vote_results.sql
\i backend/supabase/work.sql
\i backend/supabase/work_translations.sql
\i backend/supabase/profile_causes.sql
\i backend/supabase/profile_interests.sql
\i backend/supabase/profile_work.sql
\i backend/supabase/compatibility_prompts_translations.sql
\i backend/supabase/migrations/20251106_add_message_actions.sql
\i backend/supabase/migrations/20251110_add_languages_to_profiles.sql
\i backend/supabase/migrations/20251112_add_mbti_to_profiles.sql
\i backend/supabase/migrations/20260213_add_big_5_to_profiles.sql
\i backend/supabase/migrations/20260218_add_events.sql
\i backend/supabase/migrations/20260218_add_notification_templates.sql
\i backend/supabase/migrations/20260222_add_deleted_users.sql
\i backend/supabase/migrations/20260223_add_notification_template_translations.sql
\i backend/supabase/migrations/20260224_add_connection_preferences.sql
\i backend/supabase/migrations/20260225_add_keywords_to_profiles.sql
\i backend/supabase/migrations/20260308_add_importance_counts.sql
\i backend/supabase/migrations/20260319_add_compatibility_prompts_pinned.sql
\i backend/supabase/migrations/20260330_add_substance_fields_to_profiles.sql
\i backend/supabase/email_unsubscribe_tokens.sql
\i backend/supabase/migrations/20260524_add_orientation_to_profiles.sql
\i backend/supabase/migrations/20260709_add_last_checked_at_to_bookmarked_searches.sql
\i backend/supabase/migrations/20260724_add_accessibility_notes_to_profiles.sql
\i backend/supabase/migrations/20260724_add_neurotype_to_profiles.sql
\i backend/supabase/migrations/20260728_add_ban_reason_to_users.sql
\i backend/supabase/migrations/20260730_cap_profiles_users_reads.sql
\i backend/supabase/migrations/20260731_add_exercise_to_profiles.sql
\i backend/supabase/migrations/20260731_lock_activity_stars_compat.sql
\i backend/supabase/migrations/20260801_add_outreach_contacts.sql
\i backend/supabase/migrations/20260803_add_testimonials.sql
\i backend/supabase/migrations/20260803_add_outreach_sends.sql
\i backend/supabase/migrations/20260804_add_search_alert_sends.sql
\i backend/supabase/migrations/20260806_add_feed_visibility_to_profiles.sql
\i backend/supabase/migrations/20260808_add_vote_comments.sql
\i backend/supabase/migrations/20260808_extend_vote_comment_stances.sql
\i backend/supabase/migrations/20260808_vote_top_arguments.sql
COMMIT;
