-- This file is autogenerated from regen-schema.ts
CREATE TABLE IF NOT EXISTS private_user_message_channels (
    created_time TIMESTAMPTZ DEFAULT now() NOT NULL,
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    last_updated_time TIMESTAMPTZ DEFAULT now() NOT NULL,
    title TEXT,
    CONSTRAINT private_user_message_channels_pkey PRIMARY KEY (id)
);

-- Row Level Security
ALTER TABLE private_user_message_channels ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "public read" ON private_user_message_channels;

CREATE POLICY "public read" ON private_user_message_channels
    FOR ALL
    USING (true);

-- Indexes
-- Removed redundant primary key index creation because PRIMARY KEY already creates a unique index on id
