name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

  test:
    name: Jest Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run Jest tests
        env:
          NEXT_PUBLIC_FIREBASE_ENV: DEV
        run: |
          yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            backend/api/coverage/lcov.info
            backend/shared/coverage/lcov.info
            backend/email/coverage/lcov.info
            common/coverage/lcov.info
            web/coverage/lcov.info
          flags: unit
          fail_ci_if_error: true
          slug: CompassConnections/Compass
